package matchsig

import (
	"encoding/json"
	"math/big"
	"os"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
)

// vectorsPath points at the committed golden-vector file generated by
// extension/matcher/cmd/genvectors and consumed by extension/matcher/vectors_test.go +
// contracts/test/GoldenVectors.t.sol. The task description mentions extension/matcher/testdata —
// that directory does not exist in this checkout; this is the actual location (documented in
// extension/fcewire/PROTOCOL.md §10). Relative to this package's directory
// (scripts/enclave-loop/internal/matchsig), which is `go test`'s working directory by default.
const vectorsPath = "../../../../contracts/test/vectors/matchinstruction.json"

type vectorFile struct {
	WDMatchTag string   `json:"wdMatchTag"`
	Vectors    []vector `json:"vectors"`
}

type vector struct {
	Name            string `json:"name"`
	ChainID         string `json:"chainId"`
	AbiEncoded      string `json:"abiEncoded"`
	DataHash        string `json:"dataHash"`
	EthSignedDigest string `json:"ethSignedDigest"`
	Signature       string `json:"signature"`
	ExpectedSigner  string `json:"expectedSigner"`
}

func loadVectors(t *testing.T) vectorFile {
	t.Helper()
	b, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("reading %s: %v (run `go run ./cmd/genvectors` from extension/matcher first)", vectorsPath, err)
	}
	var vf vectorFile
	if err := json.Unmarshal(b, &vf); err != nil {
		t.Fatalf("unmarshaling %s: %v", vectorsPath, err)
	}
	if len(vf.Vectors) == 0 {
		t.Fatalf("%s has zero vectors", vectorsPath)
	}
	return vf
}

func mustHexUint64(t *testing.T, s string) uint64 {
	t.Helper()
	s = strings.TrimPrefix(s, "0x")
	v, ok := new(big.Int).SetString(s, 16)
	if !ok {
		t.Fatalf("bad hex uint64 %q", s)
	}
	return v.Uint64()
}

// TestWDMatchTagMatchesVectors pins this package's WDMatchTag() against the committed vectors
// file's recorded value — same cross-check role as extension/matcher/vectors_test.go's
// TestWDMatchTag.
func TestWDMatchTagMatchesVectors(t *testing.T) {
	vf := loadVectors(t)
	tag := WDMatchTag()
	got := "0x" + common.Bytes2Hex(tag[:])
	if !strings.EqualFold(got, vf.WDMatchTag) {
		t.Fatalf("WDMatchTag() = %s, vectors file says %s", got, vf.WDMatchTag)
	}
}

// TestGoldenVectors_DigestAndRecover asserts wd-client's independently-ported DataHash /
// EthSignedDigest / Recover reproduce every recorded value byte-for-byte AND that Recover on the
// vector's own signature+digest returns the recorded expectedSigner — this is the exact chain
// wd-client's `loop` subcommand runs against a live MatchResponse before trusting it.
func TestGoldenVectors_DigestAndRecover(t *testing.T) {
	vf := loadVectors(t)

	for _, v := range vf.Vectors {
		v := v
		t.Run(v.Name, func(t *testing.T) {
			chainID := mustHexUint64(t, v.ChainID)
			abiEncoded := common.FromHex(v.AbiEncoded)

			dHash := DataHash(abiEncoded)
			if !strings.EqualFold(dHash.Hex(), v.DataHash) {
				t.Fatalf("DataHash mismatch: got %s want %s", dHash.Hex(), v.DataHash)
			}

			digest := EthSignedDigest(dHash, chainID)
			if !strings.EqualFold(digest.Hex(), v.EthSignedDigest) {
				t.Fatalf("EthSignedDigest mismatch: got %s want %s", digest.Hex(), v.EthSignedDigest)
			}

			sig := common.FromHex(v.Signature)
			recovered, err := Recover(digest, sig)
			if err != nil {
				t.Fatalf("Recover: %v", err)
			}
			want := common.HexToAddress(v.ExpectedSigner)
			if recovered != want {
				t.Fatalf("Recover() = %s, want %s", recovered.Hex(), want.Hex())
			}

			// VerifyMatch is the actual call site `loop` uses — exercise it end-to-end too.
			verified, err := VerifyMatch(abiEncoded, sig, chainID, want)
			if err != nil {
				t.Fatalf("VerifyMatch: unexpected error: %v", err)
			}
			if verified != want {
				t.Fatalf("VerifyMatch returned %s, want %s", verified.Hex(), want.Hex())
			}
		})
	}
}

// TestGoldenVectors_RejectsTamperedSignature is a negative control mirroring
// extension/matcher/vectors_test.go's TestGoldenVectors_RejectsTamperedSignature: flipping one
// byte of a vector's signature must NOT recover the expected signer, and VerifyMatch must return
// an error rather than silently accepting it.
func TestGoldenVectors_RejectsTamperedSignature(t *testing.T) {
	vf := loadVectors(t)
	v := vf.Vectors[0]
	chainID := mustHexUint64(t, v.ChainID)
	abiEncoded := common.FromHex(v.AbiEncoded)

	sig := common.FromHex(v.Signature)
	tampered := append([]byte(nil), sig...)
	tampered[0] ^= 0xFF // flip a byte of R

	want := common.HexToAddress(v.ExpectedSigner)

	dHash := DataHash(abiEncoded)
	digest := EthSignedDigest(dHash, chainID)
	recovered, err := Recover(digest, tampered)
	if err == nil && recovered == want {
		t.Fatalf("tampered signature still recovered the expected signer — negative control is broken")
	}

	if _, err := VerifyMatch(abiEncoded, tampered, chainID, want); err == nil {
		t.Fatalf("VerifyMatch: expected an error for a tampered signature, got nil")
	}
}
