// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.25;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {MatchInstructionLib} from "../src/libraries/MatchInstructionLib.sol";

/// @notice Cross-language (Go <-> Solidity) byte-parity test for MatchInstructionLib
/// (design.md §3.5/§6.3, Step 4 DoD). Reads the SAME golden-vector fixture that
/// extension/matcher/vectors_test.go reads (contracts/test/vectors/matchinstruction.json,
/// generated by extension/matcher/cmd/genvectors — single source of truth, do not hand-edit) and
/// asserts that Solidity's abi.encode(mi) / MatchInstructionLib.dataHash / .ethSignedDigest /
/// ecrecover reproduce byte-for-byte what the Go matcher package independently computed and
/// signed. Any drift between the two languages' ABI encoding or digest construction — the exact
/// class of bug that would silently break DvPEscrow.lock() in production — fails this test.
contract GoldenVectorsTest is Test {
    using stdJson for string;

    string internal json;
    uint256 internal count;

    function setUp() public {
        string memory path = string.concat(vm.projectRoot(), "/test/vectors/matchinstruction.json");
        json = vm.readFile(path);
        count = json.readUint(".count");
    }

    function test_VectorFileIsNonEmpty() public view {
        assertGt(count, 0, "matchinstruction.json has zero vectors -- run `go run ./cmd/genvectors`");
        assertEq(count, json.readUint(".count"), "sanity: count field readable twice");
    }

    function test_WDMatchTag_MatchesGoSide() public view {
        bytes32 wantTag = json.readBytes32(".wdMatchTag");
        assertEq(MatchInstructionLib.WD_MATCH_TAG, wantTag, "WD_MATCH_TAG drifted from the Go vectors file");
    }

    /// @notice For every vector: rebuild the MatchInstruction struct from the JSON fields,
    /// re-encode/hash/digest it in Solidity, and assert each intermediate value matches what Go
    /// (extension/matcher) independently produced — plus that ecrecover over the committed
    /// signature recovers the committed signer, and that signer is exactly what the vector's own
    /// private key derives (so the fixture itself is internally consistent, not just self-similar).
    function test_GoldenVectors_EncodingHashDigestAndRecover() public {
        for (uint256 i = 0; i < count; i++) {
            _checkVector(i);
        }
    }

    function _checkVector(uint256 i) internal {
        string memory base = string.concat(".vectors[", vm.toString(i), "]");
        string memory name = json.readString(string.concat(base, ".name"));

        MatchInstructionLib.MatchInstruction memory mi = MatchInstructionLib.MatchInstruction({
            matchId: json.readBytes32(string.concat(base, ".matchId")),
            escrow: json.readAddress(string.concat(base, ".escrow")),
            taker: json.readAddress(string.concat(base, ".taker")),
            maker: json.readAddress(string.concat(base, ".maker")),
            amountFxrp: json.readUint(string.concat(base, ".amountFxrp")),
            priceUsd18: json.readUint(string.concat(base, ".priceUsd18")),
            takerXrplAddress: json.readString(string.concat(base, ".takerXrplAddress")),
            instructionExpiresAt: uint64(json.readUint(string.concat(base, ".instructionExpiresAt")))
        });
        uint256 chainId = json.readUint(string.concat(base, ".chainId"));

        // --- ABI encoding parity -------------------------------------------------------------
        bytes memory encoded = abi.encode(mi);
        bytes memory wantEncoded = json.readBytes(string.concat(base, ".abiEncoded"));
        assertEq(encoded, wantEncoded, string.concat(name, ": abi.encode(mi) mismatch"));

        // --- dataHash parity -------------------------------------------------------------------
        bytes32 dataHash = MatchInstructionLib.dataHash(encoded);
        bytes32 wantDataHash = json.readBytes32(string.concat(base, ".dataHash"));
        assertEq(dataHash, wantDataHash, string.concat(name, ": dataHash mismatch"));

        // --- ethSignedDigest parity --------------------------------------------------------------
        bytes32 digest = MatchInstructionLib.ethSignedDigest(dataHash, chainId);
        bytes32 wantDigest = json.readBytes32(string.concat(base, ".ethSignedDigest"));
        assertEq(digest, wantDigest, string.concat(name, ": ethSignedDigest mismatch"));

        // --- signature / ecrecover parity --------------------------------------------------------
        bytes memory sig = json.readBytes(string.concat(base, ".signature"));
        assertEq(sig.length, 65, string.concat(name, ": signature must be 65 bytes"));
        (bytes32 r, bytes32 s, uint8 v) = _splitSignature(sig);
        assertTrue(v == 27 || v == 28, string.concat(name, ": V must be 27 or 28"));

        address recovered = ecrecover(digest, v, r, s);
        assertTrue(recovered != address(0), string.concat(name, ": ecrecover returned the zero address"));

        address wantSigner = json.readAddress(string.concat(base, ".expectedSigner"));
        assertEq(recovered, wantSigner, string.concat(name, ": ecrecover(digest, sig) != expectedSigner"));

        // Internal-consistency check: the vector's own recorded private key must independently
        // derive the same expectedSigner address (guards against a stale/mismatched fixture).
        uint256 privKey = json.readUint(string.concat(base, ".teeSignerPrivateKey"));
        assertEq(vm.addr(privKey), wantSigner, string.concat(name, ": vm.addr(teeSignerPrivateKey) != expectedSigner"));

        // --- decode round-trip -------------------------------------------------------------------
        MatchInstructionLib.MatchInstruction memory decoded = MatchInstructionLib.decode(encoded);
        assertEq(decoded.matchId, mi.matchId, string.concat(name, ": decode().matchId"));
        assertEq(decoded.escrow, mi.escrow, string.concat(name, ": decode().escrow"));
        assertEq(decoded.taker, mi.taker, string.concat(name, ": decode().taker"));
        assertEq(decoded.maker, mi.maker, string.concat(name, ": decode().maker"));
        assertEq(decoded.amountFxrp, mi.amountFxrp, string.concat(name, ": decode().amountFxrp"));
        assertEq(decoded.priceUsd18, mi.priceUsd18, string.concat(name, ": decode().priceUsd18"));
        assertEq(decoded.takerXrplAddress, mi.takerXrplAddress, string.concat(name, ": decode().takerXrplAddress"));
        assertEq(
            decoded.instructionExpiresAt, mi.instructionExpiresAt, string.concat(name, ": decode().instructionExpiresAt")
        );
    }

    /// @notice Negative control: flipping one byte of a vector's signature must NOT recover the
    /// expected signer — guards against a vacuously-true comparison in the positive test above.
    function test_TamperedSignature_DoesNotRecoverExpectedSigner() public view {
        string memory base = ".vectors[0]";
        bytes32 dataHash = json.readBytes32(string.concat(base, ".dataHash"));
        uint256 chainId = json.readUint(string.concat(base, ".chainId"));
        bytes32 digest = MatchInstructionLib.ethSignedDigest(dataHash, chainId);

        bytes memory sig = json.readBytes(string.concat(base, ".signature"));
        sig[0] = bytes1(uint8(sig[0]) ^ 0xFF); // flip a byte of R

        (bytes32 r, bytes32 s, uint8 v) = _splitSignature(sig);
        address recovered = ecrecover(digest, v, r, s);

        address wantSigner = json.readAddress(string.concat(base, ".expectedSigner"));
        assertTrue(recovered != wantSigner, "tampered signature still recovered the expected signer");
    }

    function _splitSignature(bytes memory sig) internal pure returns (bytes32 r, bytes32 s, uint8 v) {
        require(sig.length == 65, "bad signature length");
        assembly {
            r := mload(add(sig, 32))
            s := mload(add(sig, 64))
            v := byte(0, mload(add(sig, 96)))
        }
    }
}
