// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.25;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {DvPEscrow} from "../src/DvPEscrow.sol";
import {BondLedger} from "../src/BondLedger.sol";
import {MockFXRP} from "../src/mocks/MockFXRP.sol";
import {MockFtsoV2} from "../src/mocks/MockFtsoV2.sol";
import {MockFdcVerification} from "../src/mocks/MockFdcVerification.sol";

/// @title MatcherToLock
/// @notice Step 5: closes the Go-matcher -> Solidity loop. `GoldenVectors.t.sol` (Step 4) already
/// proves byte-for-byte parity between the Go `extension/matcher` package's ABI encoding /
/// dataHash / ethSignedDigest / signature and Solidity's independent recomputation of the same —
/// i.e. that the DIGEST AND SIGNATURE are correct. What it does NOT prove is that those exact bytes
/// are actually *accepted* by `DvPEscrow.lock()` end-to-end. This file does: it takes one golden
/// vector's exact `abiEncoded` instructionData + `signature` bytes (produced entirely by the Go
/// side, per `contracts/test/vectors/matchinstruction.json`, generated by
/// `extension/matcher/cmd/genvectors` — not re-signed here) and feeds them through a real
/// `DvPEscrow.lock()` call, with `teeSigner` set to the vector's own `expectedSigner`.
///
/// The tricky part: `lock()` requires `mi.escrow == address(this)` (design.md §3.5 cross-instance
/// replay guard), and the golden vector's `escrow` field is a fixed test address
/// (`0x00000000000000000000000000000000000000e1`) baked into the signed bytes — it cannot be
/// changed without invalidating the Go-produced signature. So this test pins a real `DvPEscrow`
/// instance to that EXACT address using `vm.etch` (copies the runtime bytecode of a normally
/// `new`-deployed instance, which already has this test's real FXRP/BondLedger/window immutables
/// resolved into it) plus `vm.store` (writes the handful of ordinary — non-immutable — storage
/// slots a constructor would otherwise have set: `owner`, `teeSigner`, `ftsoV2`, `fdcVerification`,
/// `feeTreasury`, `nextDestinationTag`; slot numbers taken from `forge inspect DvPEscrow
/// storage-layout`, reproduced in the comment on `_pinEscrowAt` below). This is standard-but-
/// low-level Foundry technique for pinning a contract to an address CREATE/CREATE2 cannot reach
/// deterministically; it is not a shortcut around any DvPEscrow check — `lock()` runs unmodified.
contract MatcherToLockTest is Test {
    using stdJson for string;

    // Storage slots per `forge inspect DvPEscrow storage-layout` (contracts/src/DvPEscrow.sol):
    //   slot 0        owner                (address, 20 bytes)
    //   slot 1        teeSigner            (address, 20 bytes)
    //   slot 2        ftsoV2               (address, 20 bytes)
    //   slot 3        fdcVerification      (address, 20 bytes)
    //   slot 4[0:20]  feeTreasury          (address, 20 bytes) — packed with lockPaused at [20]
    //   slot 5        balances             (mapping — base slot only, no direct value)
    //   slot 6        matches              (mapping — base slot only, no direct value)
    //   slot 7        nextDestinationTag   (uint32) — initializer `= 1` is constructor-run code,
    //                                      not baked into runtime bytecode, so etch needs it set
    //   slot 8        usedTxId             (mapping — base slot only, no direct value)
    uint256 internal constant SLOT_OWNER = 0;
    uint256 internal constant SLOT_TEE_SIGNER = 1;
    uint256 internal constant SLOT_FTSOV2 = 2;
    uint256 internal constant SLOT_FDC_VERIFICATION = 3;
    uint256 internal constant SLOT_FEE_TREASURY = 4;
    uint256 internal constant SLOT_NEXT_DESTINATION_TAG = 7;

    MockFXRP internal fxrp;
    BondLedger internal bondLedger;
    MockFtsoV2 internal ftso;
    MockFdcVerification internal fdc;

    address internal owner = makeAddr("owner");
    address internal feeTreasury = makeAddr("feeTreasury");
    address internal relayer = makeAddr("relayer");

    string internal json;

    function setUp() public {
        vm.startPrank(owner);
        fxrp = new MockFXRP();
        bondLedger = new BondLedger(fxrp);
        ftso = new MockFtsoV2();
        fdc = new MockFdcVerification();
        vm.stopPrank();

        ftso.setFee(0);

        string memory path = string.concat(vm.projectRoot(), "/test/vectors/matchinstruction.json");
        json = vm.readFile(path);
    }

    /// @dev Deploys a throwaway DvPEscrow (to obtain correctly-immutable-patched runtime
    /// bytecode), etches that code to `target`, then writes the ordinary storage slots a
    /// constructor call would have set. `target` ends up behaviorally identical to a freshly
    /// `new`-deployed DvPEscrow with the given config, EXCEPT its address is caller-chosen.
    function _pinEscrowAt(address target, address teeSigner_, uint32 settlementWindow, uint32 attestationBudget)
        internal
        returns (DvPEscrow escrow)
    {
        DvPEscrow tmp = new DvPEscrow(
            fxrp, bondLedger, teeSigner_, ftso, fdc, bytes32("testXRP"), feeTreasury, settlementWindow, attestationBudget
        );
        vm.etch(target, address(tmp).code);

        vm.store(target, bytes32(SLOT_OWNER), bytes32(uint256(uint160(owner))));
        vm.store(target, bytes32(SLOT_TEE_SIGNER), bytes32(uint256(uint160(teeSigner_))));
        vm.store(target, bytes32(SLOT_FTSOV2), bytes32(uint256(uint160(address(ftso)))));
        vm.store(target, bytes32(SLOT_FDC_VERIFICATION), bytes32(uint256(uint160(address(fdc)))));
        vm.store(target, bytes32(SLOT_FEE_TREASURY), bytes32(uint256(uint160(feeTreasury)))); // lockPaused=false (0)
        vm.store(target, bytes32(SLOT_NEXT_DESTINATION_TAG), bytes32(uint256(1)));

        escrow = DvPEscrow(target);
    }

    /// @notice Feeds the "happy-path-min-block" golden vector's exact Go-produced instructionData
    /// + signature through a real `lock()` call and asserts it opens the match.
    function test_GoldenVector_HappyPathMinBlock_AcceptedByLock() public {
        string memory base = ".vectors[0]";
        assertEq(json.readString(string.concat(base, ".name")), "happy-path-min-block", "wrong vector index");

        address vecEscrow = json.readAddress(string.concat(base, ".escrow"));
        address vecTaker = json.readAddress(string.concat(base, ".taker"));
        address vecMaker = json.readAddress(string.concat(base, ".maker"));
        uint256 vecAmountFxrp = json.readUint(string.concat(base, ".amountFxrp"));
        uint256 vecPriceUsd18 = json.readUint(string.concat(base, ".priceUsd18"));
        uint256 vecChainId = json.readUint(string.concat(base, ".chainId"));
        uint256 vecExpiresAt = json.readUint(string.concat(base, ".instructionExpiresAt"));
        bytes32 vecMatchId = json.readBytes32(string.concat(base, ".matchId"));
        address vecSigner = json.readAddress(string.concat(base, ".expectedSigner"));
        bytes memory abiEncoded = json.readBytes(string.concat(base, ".abiEncoded"));
        bytes memory signature = json.readBytes(string.concat(base, ".signature"));

        // This vector's amountFxrp is exactly MIN_BLOCK_FXRP (5_000e6) — confirm the fixture
        // still matches DvPEscrow's live constant, so this test fails loudly (not silently) if
        // either side's constant ever drifts.
        assertEq(vecAmountFxrp, 5_000e6, "golden vector amountFxrp no longer equals MIN_BLOCK_FXRP");

        vm.chainId(vecChainId);
        vm.warp(1_700_000_000); // well before vecExpiresAt (0x6b49d200 = 1_799_759_872), after epoch 0
        assertLt(block.timestamp, vecExpiresAt, "warped past the vector's instructionExpiresAt");

        DvPEscrow escrow = _pinEscrowAt(vecEscrow, vecSigner, 1800, 360);
        vm.prank(owner);
        bondLedger.setEscrow(address(escrow));

        // FTSOv2 band re-check inside lock(): set the live mid to exactly the vector's signed
        // price so the +/-1% band trivially passes without altering any signed field.
        ftso.setFeed(vecPriceUsd18, uint64(block.timestamp));

        fxrp.mint(vecTaker, vecAmountFxrp);
        vm.startPrank(vecTaker);
        fxrp.approve(address(escrow), vecAmountFxrp);
        escrow.deposit(vecAmountFxrp, uint64(block.timestamp + 3600));
        vm.stopPrank();

        uint256 bondAmount = vecAmountFxrp / 100; // BOND_BIPS = 100 (1%)
        fxrp.mint(vecMaker, bondAmount);
        vm.startPrank(vecMaker);
        fxrp.approve(address(bondLedger), bondAmount);
        bondLedger.depositBond(bondAmount);
        vm.stopPrank();

        vm.prank(relayer);
        bytes32 matchId = escrow.lock(abiEncoded, signature);

        assertEq(matchId, vecMatchId, "lock() returned a different matchId than the signed vector's");
        (
            address mTaker,
            ,
            ,
            DvPEscrow.MatchState state,
            address mMaker,
            ,
            ,
            uint128 mAmountFxrp,
            ,
            ,
        ) = escrow.matches(matchId);
        assertEq(uint8(state), uint8(DvPEscrow.MatchState.Locked), "match not Locked after lock()");
        assertEq(mTaker, vecTaker, "match.taker mismatch");
        assertEq(mMaker, vecMaker, "match.maker mismatch");
        assertEq(mAmountFxrp, vecAmountFxrp, "match.amountFxrp mismatch");
    }

    /// @notice Negative control: the same instructionData with `teeSigner` left at a DIFFERENT
    /// address must be rejected — confirms the success above is because of the signature, not
    /// because lock()'s signer check is vacuous.
    function test_GoldenVector_WrongTeeSigner_Reverts() public {
        string memory base = ".vectors[0]";
        address vecEscrow = json.readAddress(string.concat(base, ".escrow"));
        uint256 vecChainId = json.readUint(string.concat(base, ".chainId"));
        bytes memory abiEncoded = json.readBytes(string.concat(base, ".abiEncoded"));
        bytes memory signature = json.readBytes(string.concat(base, ".signature"));

        vm.chainId(vecChainId);
        vm.warp(1_700_000_000);

        address wrongSigner = makeAddr("wrongTeeSigner");
        DvPEscrow escrow = _pinEscrowAt(vecEscrow, wrongSigner, 1800, 360);
        vm.prank(owner);
        bondLedger.setEscrow(address(escrow));

        vm.prank(relayer);
        vm.expectRevert(); // InvalidTeeSignature(recovered) — recovered != wrongSigner
        escrow.lock(abiEncoded, signature);
    }
}
